### ISSUE TITLE
time management?

### ISSUE THREAD

**Issue by jdsutherland** [naggie/dotfiles#174]
I noticed the line about time management: https://github.com/naggie/dotfiles/blob/master/README.md?plain=1#L19, but I'm not sure what it's referencing. I'm curious if you use something like timewarrior or do you find it unnecessary?

**Comment by naggie** [comment]
Ah yes, that's just because I never wrote that section. I don't use timewarrior or the like. Right now I just use dstask and that seems sufficient, in combination with some markdown notes and the odd gantt chart.
